In [6]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

1. Scrape the details of most viewed videos on YouTube from Wikipedia. Url 
= https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:
A)Rank 
B) Name 
C) Artist 
D) Upload date 
E) Views

In [10]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import pandas as pd
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
Rank=[]
Name=[]
Artist=[]
Upload_Date=[]
Views=[]
#scraping the Rank 
rk=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[2]/tbody/tr/td[1]")
for i in rk:
    if i.text is None :
        Rank.append("--") 
    else:
        Rank.append(i.text)
print(len(Rank),Rank)

#scraping the Video Name 
nm=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[2]/tbody/tr/td[2]")
for i in nm:
    if i.text is None :
        Name.append("--") 
    else:
        Name.append(i.text)
print(len(Name),Name)

#scraping the Artist 
Ar=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[2]/tbody/tr/td[3]")
for i in Ar:
    if i.text is None :
        Artist.append("--") 
    else:
        Artist.append(i.text)
print(len(Artist),Artist)

#scraping the Upload_Date 
date=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[2]/tbody/tr/td[5]")
for i in date:
    if i.text is None :
        Upload_Date.append("--") 
    else:
        Upload_Date.append(i.text)
print(len(Upload_Date),Upload_Date)

#scraping the Views 
v=driver.find_elements(By.XPATH,"//*[@id='mw-content-text']/div[1]/table[2]/tbody/tr/td[4]")
for i in v:
    if i.text is None :
        Views.append("--") 
    else:
        Views.append(i.text)
print(len(Views),Views)

Youtube_Video=pd.DataFrame([])
Youtube_Video['Rank']=Rank
Youtube_Video['Video Title']=Name
Youtube_Video['Artist']=Artist
Youtube_Video['Upload_Date']=Upload_Date
Youtube_Video['Views In Bllion']=Views
Youtube_Video

30 ['"Baby Shark Dance"[6]', '"Despacito"[9]', '"Johny Johny Yes Papa"[17]', '"Bath Song"[18]', '"Shape of You"[19]', '"See You Again"[22]', '"Wheels on the Bus"[27]', '"Phonics Song with Two Words"[28]', '"Uptown Funk"[29]', '"Learning Colors – Colorful Eggs on a Farm"[30]', '"Gangnam Style"[31]', '"Masha and the Bear – Recipe for Disaster"[36]', '"Dame Tu Cosita"[37]', '"Axel F"[38]', '"Sugar"[39]', '"Counting Stars"[40]', '"Baa Baa Black Sheep"[41]', '"Roar"[42]', '"Lakdi Ki Kathi"[43]', '"Waka Waka (This Time for Africa)"[44]', '"Sorry"[45]', '"Thinking Out Loud"[46]', '"Humpty the train on a fruits ride"[47]', '"Shree Hanuman Chalisa"[48]', '"Dark Horse"[49]', '"Perfect"[50]', '"Let Her Go"[51]', '"Faded"[52]', '"Girls Like You"[53]', '"Lean On"[54]']
30 ["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', "LooLoo Kids - Nursery Rhymes and Children's Songs", 'Cocomelon - Nursery Rhymes', 'Ed Sheeran', 'Wiz Khalifa', 'Cocomelon - Nursery Rhymes', 'ChuChu TV Nursery Rhymes & Kids Songs', 'Mark Ronson', 'Miroshka TV', 'Psy', 'Get Movies', 'Ultra Records', 'Crazy Frog', 'Maroon 5', 'OneRepublic', 'Cocomelon - Nursery Rhymes', 'Katy Perry', 'Jingle Toons', 'Shakira', 'Justin Bieber', 'Ed Sheeran', 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs', 'T-Series Bhakti Sagar', 'Katy Perry', 'Ed Sheeran', 'Passenger', 'Alan Walker', 'Maroon 5', 'Major Lazer Official']
30 ['14.09', '8.38', '6.87', '6.62', '6.20', '6.17', '5.88', '5.70', '5.15', '5.07', '5.05', '4.58', '4.55', '4.34', '4.00', '3.97', '3.96', '3.96', '3.91', '3.85', '3.77', '3.73', '3.73', '3.69', '3.67', '3.67', '3.61', '3.59', '3.56', '3.55']
30 ['[A]', '[B]', '', '', '[C]', '[D]', '', '', '', '', '[E]', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
30 ['June 17, 2016', 'January 12, 2017', 'October 8, 2016', 'May 2, 2018', 'January 30, 2017', 'April 6, 2015', 'May 24, 2018', 'March 6, 2014', 'November 19, 2014', 'February 27, 2018', 'July 15, 2012', 'January 31, 2012', 'April 5, 2018', 'June 16, 2009', 'January 14, 2015', 'May 31, 2013', 'June 25, 2018', 'September 5, 2013', 'June 14, 2018', 'June 4, 2010', 'October 22, 2015', 'October 7, 2014', 'January 26, 2018', 'May 10, 2011', 'February 20, 2014', 'November 9, 2017', 'July 25, 2012', 'December 3, 2015', 'May 31, 2018', 'March 22, 2015']

,Rank,Video Title,Artist,Upload_Date,Views In Bllion
0,"""Baby Shark Dance""[6]",Pinkfong Baby Shark - Kids' Songs & Stories,14.09,[A],"June 17, 2016"
1,"""Despacito""[9]",Luis Fonsi,8.38,[B],"January 12, 2017"
2,"""Johny Johny Yes Papa""[17]",LooLoo Kids - Nursery Rhymes and Children's Songs,6.87,,"October 8, 2016"
3,"""Bath Song""[18]",Cocomelon - Nursery Rhymes,6.62,,"May 2, 2018"
4,"""Shape of You""[19]",Ed Sheeran,6.20,[C],"January 30, 2017"
5,"""See You Again""[22]",Wiz Khalifa,6.17,[D],"April 6, 2015"
6,"""Wheels on the Bus""[27]",Cocomelon - Nursery Rhymes,5.88,,"May 24, 2018"
7,"""Phonics Song with Two Words""[28]",ChuChu TV Nursery Rhymes & Kids Songs,5.70,,"March 6, 2014"
8,"""Uptown Funk""[29]",Mark Ronson,5.15,,"November 19, 2014"
9,"""Learning Colors – Colorful Eggs on a Farm""[30]",Miroshka TV,5.07,,"February 27, 2018"
10,"""Gangnam Style""[31]",Psy,5.05,[E],"July 15, 2012"
11,"""Masha and the Bear – Recipe for Disaster""[36]",Get Movies,4.58,,"January 31, 2012"
12,"""Dame Tu Cosita""[37]",Ultra Records,4.55,,"April 5, 2018"
13,"""Axel F""[38]",Crazy Frog,4.34,,"June 16, 2009"
14,"""Sugar""[39]",Maroon 5,4.00,,"January 14, 2015"
15,"""Counting Stars""[40]",OneRepublic,3.97,,"May 31, 2013"
16,"""Baa Baa Black Sheep""[41]",Cocomelon - Nursery Rhymes,3.96,,"June 25, 2018"
17,"""Roar""[42]",Katy Perry,3.96,,"September 5, 2013"
18,"""Lakdi Ki Kathi""[43]",Jingle Toons,3.91,,"June 14, 2018"
19,"""Waka Waka (This Time for Africa)""[44]",Shakira,3.85,,"June 4, 2010"
20,"""Sorry""[45]",Justin Bieber,3.77,,"October 22, 2015"
21,"""Thinking Out Loud""[46]",Ed Sheeran,3.73,,"October 7, 2014"
22,"""Humpty the train on a fruits ride""[47]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,3.73,,"January 26, 2018"
23,"""Shree Hanuman Chalisa""[48]",T-Series Bhakti Sagar,3.69,,"May 10, 2011"
24,"""Dark Horse""[49]",Katy Perry,3.67,,"February 20, 2014"
25,"""Perfect""[50]",Ed Sheeran,3.67,,"November 9, 2017"
26,"""Let Her Go""[51]",Passenger,3.61,,"July 25, 2012"
27,"""Faded""[52]",Alan Walker,3.59,,"December 3, 2015"
28,"""Girls Like You""[53]",Maroon 5,3.56,,"May 31, 2018"
29,"""Lean On""[54]",Major Lazer Official,3.55,,"March 22, 2015"

2. Scrape the details team India’s international fixtures from bcci.tv. 
Url = https://www.bcci.tv/. 
You need to find following details: 
A) Series 
B) Place 
C) Date 
D) Time 
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [5]:
import time
driver = webdriver.Chrome()
driver.get('https://www.bcci.tv')
time.sleep(5)
btn=driver.find_element(By.XPATH,'//a[@href="https://www.bcci.tv/fixtures?platform=international&type=men"]')
btn.click()
time.sleep(5)
Series=[]
Date_Time =[]
Ground=[]
Test_ODI=[]
#scraping the company_name 
tm=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')

for i in tm:
    if i.text is None :
        Team.append("--") 
    else:
        Series.append(i.text)
print(len(Series),Series)

#scraping the Date_Time 
DT=driver.find_elements(By.XPATH,'//div[@class="match-date-info"]')
for i in DT:
    if i.text is None :
        Date_Time.append("--") 
    else:
        Date_Time.append(i.text)
print(len(Date_Time),Date_Time)

#scraping the Ground 
G=driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]')
for i in G:
    if i.text is None :
        Ground.append("--") 
    else:
        Ground.append(i.text)
print(len(Ground),Ground)

# Creating a DataFrame with the correct lengths
min_length = min(len(Series), len(Date_Time), len(Ground))
International_Fixtures = pd.DataFrame({
    'Series': Series[:min_length],
    'Date_Time': Date_Time[:min_length],
    'Ground': Ground[:min_length]
})

International_Fixtures

7 ['ENGLAND TOUR OF INDIA 2023-24', 'ENGLAND TOUR OF INDIA 2023-24', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024', 'INDIA TOUR OF ZIMBABWE 2024']
7 ['23 FEBRUARY, 2024\n9:30 AM IST', '7 MARCH, 2024\n9:30 AM IST', '6 JULY, 2024\n8:00 PM IST', '7 JULY, 2024\n8:00 PM IST', '10 JULY, 2024\n8:00 PM IST', '13 JULY, 2024\n8:00 PM IST', '14 JULY, 2024\n8:00 PM IST']
6 ['Himachal Pradesh Cricket Association Stadium, Dharamsala', 'Harare Sports Club, Harare', 'Harare Sports Club, Harare', 'Harare Sports Club, Harare', 'Harare Sports Club, Harare', 'Harare Sports Club, Harare']

,Series,Date_Time,Ground
0,ENGLAND TOUR OF INDIA 2023-24,"23 FEBRUARY, 2024\n9:30 AM IST","Himachal Pradesh Cricket Association Stadium, ..."
1,ENGLAND TOUR OF INDIA 2023-24,"7 MARCH, 2024\n9:30 AM IST","Harare Sports Club, Harare"
2,INDIA TOUR OF ZIMBABWE 2024,"6 JULY, 2024\n8:00 PM IST","Harare Sports Club, Harare"
3,INDIA TOUR OF ZIMBABWE 2024,"7 JULY, 2024\n8:00 PM IST","Harare Sports Club, Harare"
4,INDIA TOUR OF ZIMBABWE 2024,"10 JULY, 2024\n8:00 PM IST","Harare Sports Club, Harare"
5,INDIA TOUR OF ZIMBABWE 2024,"13 JULY, 2024\n8:00 PM IST","Harare Sports Club, Harare"

3. Scrape the details of State-wise GDP of India from statisticstime.com. 
Url = http://statisticstimes.com/ 
You have to find following details: A) Rank 
B) State 
C) GSDP(18-19)- at current prices 
D) GSDP(19-20)- at current prices 
E) Share(18-19) 
F) GDP($ billion) 
Note: - From statisticstimes home page you have to reach to economy page through code.

In [8]:
driver = webdriver.Chrome()
driver.get('http://statisticstimes.com/')
Rank=[]
State =[]
GDP=[]
GSDP_Current=[]
GSDP_Previous=[]
Share=[]

economy = driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/button')       
economy.click()
time.sleep(5)

ind = driver.find_element(By.XPATH,'//*[@id="top"]/div[2]/div[2]/div/a[3]')       
ind.click()
time.sleep(5)

gdp = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')      
gdp.click()
time.sleep(5)

#scraping the Rank 
r=driver.find_elements(By.XPATH,"//td[@class='data1']")
for i in r:
    if i.text is None :
        Rank.append("--") 
    else:
        Rank.append(i.text)
print(len(Rank),Rank)

#scraping the State 
St=driver.find_elements(By.XPATH,"//td[@class='name']")
for i in St:
    if i.text is None :
        State.append("--") 
    else:
        State.append(i.text)
print(len(State),State)

#scraping the GDP 
gdp=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[6]")
for i in gdp:
    if i.text is None :
        GDP.append("--") 
    else:
        GDP.append(i.text)
print(len(GDP),GDP)

#scraping the Share 
shr=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[5]")
for i in shr:
    if i.text is None :
        Share.append("--") 
    else:
        Share.append(i.text)
print(len(Share),Share)

#scraping the GSDP_Current 
shr=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[4]")
for i in shr:
    if i.text is None :
        GSDP_Current.append("--") 
    else:
        GSDP_Current.append(i.text)
print(len(GSDP_Current),GSDP_Current)

#scraping the GSDP_Previous 
shr=driver.find_elements(By.XPATH,"//*[@id='table_id']/tbody/tr/td[8]")
for i in shr:
    if i.text is None :
        GSDP_Previous.append("--") 
    else:
        GSDP_Previous.append(i.text)
print(len(GSDP_Previous),GSDP_Previous)

State_GDP=pd.DataFrame([])
State_GDP['Rank']=Rank[:33]
State_GDP['State']=State[:33]
State_GDP['Share In GDP']=Share[:33]
State_GDP['GDP of State']=GDP[:33]
State_GDP['GSDP_Current']=GSDP_Current[:33]
State_GDP['GSDP_Previous']=GSDP_Previous[:33]
State_GDP

68 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '']
68 ['Maharashtra', 'Tamil Nadu', 'Uttar Pradesh', 'Karnataka', 'Gujarat', 'West Bengal', 'Rajasthan', 'Madhya Pradesh', 'Andhra Pradesh', 'Telangana', 'Kerala', 'Delhi', 'Haryana', 'Odisha', 'Bihar', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir-UT', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'India', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Madhya Pradesh', 'Telangana', 'Andhra Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Odisha', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir-UT', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Manipur', 'Arunachal Pradesh', 'Sikkim', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'India']
33 ['417.163', '278.011', '265.024', '263.440', '259.996', '183.068', '163.507', '152.494', '152.185', '151.523', '125.157', '121.422', '116.862', '90.047', '87.284', '82.442', '55.381', '54.550', '48.167', '36.530', '26.833', '23.659', '11.087', '8.396', '6.125', '5.938', '5.206', '5.041', '4.912', '4.714', '4.283', '3.735', '1.392']
33 ['13.24%', '8.82%', '8.41%', '8.36%', '8.25%', '5.81%', '5.19%', '4.84%', '4.83%', '4.81%', '3.97%', '3.85%', '3.71%', '2.86%', '2.77%', '2.62%', '1.76%', '1.73%', '1.53%', '1.16%', '0.85%', '0.75%', '0.35%', '0.27%', '0.19%', '0.19%', '0.17%', '0.16%', '0.16%', '0.15%', '0.14%', '0.12%', '0.04%']
33 ['3,108,022', '2,071,286', '1,974,532', '1,962,725', '1,937,066', '1,363,926', '1,218,193', '1,136,137', '1,133,837', '1,128,907', '932,470', '904,642', '870,665', '670,881', '650,302', '614,227', '412,612', '406,416', '358,863', '272,159', '199,917', '176,269', '82,604', '62,550', '45,635', '44,238', '38,785', '37,557', '36,594', '35,124', '31,913', '27,824', '10,371']
33 ['2,027,971', '1,343,287', '1,204,660', '1,229,713', '1,372,204', '787,758', '738,922', '600,689', '704,889', '674,371', '572,747', '597,765', '568,086', '432,960', '399,930', '433,769', '262,523', '267,681', '243,348', '193,412', '124,728', '126,433', '55,548', '39,487', '30,287', '27,834', '24,267', '20,728', '20,515', '19,801', '18,363', '18,494', '7,172']

,Rank,State,Share In GDP,GDP of State,GSDP_Current,GSDP_Previous
0,1,Maharashtra,13.24%,417.163,"3,108,022","2,027,971"
1,2,Tamil Nadu,8.82%,278.011,"2,071,286","1,343,287"
2,3,Uttar Pradesh,8.41%,265.024,"1,974,532","1,204,660"
3,4,Karnataka,8.36%,263.440,"1,962,725","1,229,713"
4,5,Gujarat,8.25%,259.996,"1,937,066","1,372,204"
5,6,West Bengal,5.81%,183.068,"1,363,926","787,758"
6,7,Rajasthan,5.19%,163.507,"1,218,193","738,922"
7,8,Madhya Pradesh,4.84%,152.494,"1,136,137","600,689"
8,9,Andhra Pradesh,4.83%,152.185,"1,133,837","704,889"
9,10,Telangana,4.81%,151.523,"1,128,907","674,371"
10,11,Kerala,3.97%,125.157,"932,470","572,747"
11,12,Delhi,3.85%,121.422,"904,642","597,765"
12,13,Haryana,3.71%,116.862,"870,665","568,086"
13,14,Odisha,2.86%,90.047,"670,881","432,960"
14,15,Bihar,2.77%,87.284,"650,302","399,930"
15,16,Punjab,2.62%,82.442,"614,227","433,769"
16,17,Assam,1.76%,55.381,"412,612","262,523"
17,18,Chhattisgarh,1.73%,54.550,"406,416","267,681"
18,19,Jharkhand,1.53%,48.167,"358,863","243,348"
19,20,Uttarakhand,1.16%,36.530,"272,159","193,412"
20,21,Jammu & Kashmir-UT,0.85%,26.833,"199,917","124,728"
21,22,Himachal Pradesh,0.75%,23.659,"176,269","126,433"
22,23,Goa,0.35%,11.087,"82,604","55,548"
23,24,Tripura,0.27%,8.396,"62,550","39,487"
24,25,Chandigarh,0.19%,6.125,"45,635","30,287"
25,26,Puducherry,0.19%,5.938,"44,238","27,834"
26,27,Meghalaya,0.17%,5.206,"38,785","24,267"
27,28,Sikkim,0.16%,5.041,"37,557","20,728"
28,29,Manipur,0.16%,4.912,"36,594","20,515"
29,30,Arunachal Pradesh,0.15%,4.714,"35,124","19,801"
30,31,Nagaland,0.14%,4.283,"31,913","18,363"
31,32,Mizoram,0.12%,3.735,"27,824","18,494"
32,33,Andaman & Nicobar Islands,0.04%,1.392,"10,371","7,172"

4. Scrape the details of trending repositories on Github.com. 
Url = https://github.com/ 
You have to find the following details: 
A) Repository title 
B) Repository description 
C) Contributors count 
D) Language used 
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [17]:
driver = webdriver.Chrome()
driver.get('https://github.com/search?q=trending&type=repositories')

Repository_Name =[]
Repository_description=[]
Language_used_Contributors_count_Updated_Date =[]


#scraping the Repositor_Name 
RN=driver.find_elements(By.XPATH,'//span[@class="Text-sc-17v1xeu-0 qaOIC search-match"]')
for i in RN:
    if i.text is None :
        Repository_Name.append("--") 
    else:
        Repository_Name.append(i.text)
print(len(Repository_Name),Repository_Name)

#scraping the Description 
des=driver.find_elements(By.XPATH,'//span[@class="Text-sc-17v1xeu-0 kWPXhV search-match"]')
for i in des:
    if i.text is None :
        Repository_description.append("--") 
    else:
        Repository_description.append(i.text)
print(len(Repository_description),Repository_description)


#scraping the Language ,contributers count,updated date
L=driver.find_elements(By.XPATH,'//li[@class="Box-sc-g0xbh4-0 rzFjy"]')
for i in L:
    if i.text is None :
        Language_used_Contributors_count_Updated_Date.append("--") 
    else:
        Language_used_Contributors_count_Updated_Date.append(i.text)
print(len(Language_used_Contributors_count_Updated_Date),Language_used_Contributors_count_Updated_Date)

10 ['iam-abbas/Reddit-Stock-Trends', 'QasimWani/LeetHub', 'vitalets/github-trending-repos', 'mbadry1/Trending-Deep-Learning', 'GeneralMills/pytrends', 'bonfy/github-trending', 'datawrangling/trendingtopics', 'huchenme/github-trending-api', 'd3/d3', 'mitchelljy/Trending-YouTube-Scraper']
10 ['Fetch currently trending stocks on Reddit', 'Automatically sync your leetcode solutions to your github account - top 5 trending GitHub repository', 'Track GitHub trending repositories in your favorite programming language by native GitHub notifications!', 'Top 100 trending deep learning repositories sorted by the number of stars gained on a specific day.', 'Pseudo API for Google Trends', 'Tracking the most popular Github repos, update daily(Python version)', 'Rails app for tracking trends in server logs - powered by the Cloudera Hadoop Distribution on EC2', 'The missing APIs for GitHub trending projects and developers 📈', 'Bring data to life with SVG, Canvas and HTML. 📊:chart_with_upwards_trend::tada:', 'Python script that scrapes the currently trending YouTube videos in a variety of countries']
30 ['Python', '1.5k', 'Updated on Mar 24, 2022', 'JavaScript', '3.7k', 'Updated 5 days ago', 'HTML', '2.6k', 'Updated 21 days ago', 'Python', '616', 'Updated on Feb 2, 2020', 'Python', '3k', 'Updated on Jan 12', 'Python', '401', 'Updated 13 hours ago', 'Ruby', '354', 'Updated on Aug 2, 2011', 'JavaScript', '734', 'Updated on Jan 6, 2023', 'Shell', '107k', 'Updated 25 days ago', 'Python', '273', 'Updated on May 1, 2020']

5. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/ You have to find the 
following details: 
A) Song name 
B) Artist name 
C) Last week rank 
D) Peak rank 
E) Weeks on board

In [10]:
driver = webdriver.Chrome()
driver.get('https://www.billboard.com/charts/')
top100 = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//a[@href="https://www.billboard.com/charts/hot-100/"]')))
top100.click()
time.sleep(5)
Song_Name =[]
Singer=[]
rank=[]
Last_Week_Weeks_on_board=[]


#scraping the Rank 
rb=driver.find_elements(By.XPATH,'//span[@class="c-label  a-font-primary-bold-l u-font-size-32@tablet u-letter-spacing-0080@tablet"]')
for i in rb:
    if i.text is None :
        rank.append("--") 
    else:
        rank.append(i.text)
print(len(rank),rank)

#scraping the Song_Name 
son=driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/h3')
for i in son:
    if i.text is None :
        Song_Name.append("--") 
    else:
        Song_Name.append(i.text)
print(len(Song_Name),Song_Name)


#scraping the Singer 
sin=driver.find_elements(By.XPATH,'//span[@class="c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only"]')
for i in sin:
    if i.text is None :
        Singer.append("--") 
    else:
        Singer.append(i.text)
print(Singer)

lwr=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]/span')
for i in lwr:
    if i.text is None :
        Last_Week_Weeks_on_board.append("--") 
    else:
        Last_Week_Weeks_on_board.append(i.text)
print(Last_Week_Weeks_on_board)

100 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100']
100 ['Lovin On Me', "Texas Hold 'Em", 'Carnival', 'Beautiful Things', 'Lose Control', 'Cruel Summer', 'Snooze', 'I Remember Everything', 'Greedy', 'Stick Season', 'Fast Car', 'Agora Hills', 'Water', 'Last Night', 'Redrum', "Thinkin' Bout Me", 'Flowers', "Is It Over Now? (Taylor's Version) [From The Vault]", 'Paint The Town Red', 'Yeah!', 'Never Lose Me', 'La Diabla', 'Fuk Sumn', 'Pretty Little Poison', 'Houdini', 'Back To Me', 'What Was I Made For?', 'Forever', 'Where The Wild Things Are', 'Talking', 'Yes, And?', 'Made For Me', 'Burn', 'Vultures', 'The Painter', 'Good Good', 'Selfish', '16 Carriages', 'Stars', 'Everybody', 'Rich Baby Daddy', 'Feather', 'Vampire', 'On My Mama', 'Wild Ones', 'Dance The Night', 'Save Me', 'Hiss', 'Exes', 'Need A Favor', 'Truck Bed', 'Do It', 'Paid', 'Surround Sound', 'Keys To My Life', 'World On Fire', 'First Person Shooter', 'La Victima', 'Get In With Me', 'Burn It Down', 'Standing Next To You', 'Think U The Shit (Fart)', 'Praise Jah In The Moonlight', 'Paperwork', 'Beg Forgiveness', 'Man Made A Bar', 'Hoodrat', 'One Call', 'Igual Que Un Angel', 'Spin You Around (1/24)', 'FTCU', 'One Of The Girls', 'Murder On The Dancefloor', 'You Broke My Heart', 'Northern Attitude', 'FE!N', '23', 'Bandit', 'Problematic', 'Nee-nah', 'Act II: Date @ 8', 'I Can Feel It', "Mamaw's House", 'Soak City', 'Harley Quinn', "You're Gonna Go Far", 'Bellakeo', 'IDGAF', 'Yeah Glo!', "Different 'Round Here", 'She Calls Me Back', "We Don't Fight Anymore", "Good (Don't Die)", 'King', 'Coal', 'Mmhmm', 'Monaco', 'Prove It', 'Perro Negro', 'Sunday Service']
['Beyonce', '¥$: Kanye West & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', 'Benson Boone', 'Teddy Swims', 'Taylor Swift', 'SZA', 'Zach Bryan Featuring Kacey Musgraves', 'Tate McRae', 'Noah Kahan', 'Luke Combs', 'Doja Cat', 'Tyla', 'Morgan Wallen', '21 Savage', 'Morgan Wallen', 'Miley Cyrus', 'Taylor Swift', 'Doja Cat', 'Usher Featuring Lil Jon & Ludacris', 'Flo Milli', 'Xavi', '¥$: Kanye West & Ty Dolla $ign', 'Warren Zeiders', 'Dua Lipa', '¥$: Kanye West & Ty Dolla $ign', 'Billie Eilish', 'Noah Kahan', 'Luke Combs', '¥$: Kanye West & Ty Dolla $ign Featuring North West', 'Ariana Grande', 'Muni Long', '¥$: Kanye West & Ty Dolla $ign', '¥$: Kanye West & Ty Dolla $ign Featuring Lil Durk & Bump J', 'Cody Johnson', 'Usher, Summer Walker & 21 Savage', 'Justin Timberlake', 'Beyonce', '¥$: Kanye West & Ty Dolla $ign', 'Nicki Minaj Featuring Lil Uzi Vert', 'Drake Featuring Sexyy Red & SZA', 'Sabrina Carpenter', 'Olivia Rodrigo', 'Victoria Monet', 'Jessie Murph & Jelly Roll', 'Dua Lipa', 'Jelly Roll With Lainey Wilson', 'Megan Thee Stallion', 'Tate McRae', 'Jelly Roll', 'HARDY', '¥$: Kanye West & Ty Dolla $ign', '¥$: Kanye West & Ty Dolla $ign', 'JID Featuring 21 Savage & Baby Tate', '¥$: Kanye West & Ty Dolla $ign', 'Nate Smith', 'Drake Featuring J. Cole', 'Xavi', 'BossMan Dlow', 'Parker McCollum', 'Jung Kook', 'Ice Spice', 'YG Marley', '¥$: Kanye West & Ty Dolla $ign', '¥$: Kanye West & Ty Dolla $ign', 'Morgan Wallen Featuring Eric Church', '¥$: Kanye West & Ty Dolla $ign', 'Rich Amiri', 'Kali Uchis & Peso Pluma', 'Morgan Wallen', 'Nicki Minaj', 'The Weeknd, Jennie & Lily Rose Depp', 'Sophie Ellis-Bextor', 'Drake', 'Noah Kahan With Hozier', 'Travis Scott Featuring Playboi Carti', 'Chayce Beckham', 'Don Toliver', '¥$: Kanye West & Ty Dolla $ign', '21 Savage, Travis Scott & Metro Boomin', '4Batz', 'Kane Brown', 'Thomas Rhett Featuring Morgan Wallen', '310babii', 'Fuerza Regida & Marshmello', 'Noah Kahan', 'Peso Pluma & Anitta', 'Drake Featuring Yeat', 'GloRilla', 'Riley Green Featuring Luke Combs', 'Noah Kahan With Kacey Musgraves', 'Carly Pearce Featuring Chris Stapleton', '¥$: Kanye West & Ty Dolla $ign', '¥$: Kanye West & Ty Dolla $ign', 'Dylan Gossett', 'BigXthaPlug', 'Bad Bunny', '21 Savage & Summer Walker', 'Bad Bunny & Feid', 'Latto']
['1', '14', '-', '1', '-', '1', '3', '4', '2', '27', '4', '41', '5', '61', '6', '25', '7', '22', '11', '20', '8', '47', '9', '21', '12', '20', '15', '55', '14', '5', '16', '50', '10', '52', '18', '16', '17', '28', '-', '46', '19', '9', '25', '9', '-', '1', '24', '23', '22', '14', '-', '1', '20', '30', '-', '1', '26', '13', '-', '1', '21', '5', '28', '5', '-', '1', '-', '1', '30', '19', '45', '27', '23', '3', '-', '1', '-', '1', '27', '10', '32', '19', '36', '11', '29', '30', '33', '22', '35', '19', '37', '33', '40', '32', '13', '3', '34', '13', '39', '44', '46', '35', '-', '1', '-', '1', '48', '14', '-', '1', '44', '16', '47', '19', '56', '9', '68', '2', '55', '17', '81', '15', '52', '3', '60', '3', '-', '1', '-', '1', '63', '21', '-', '1', '64', '3', '53', '5', '51', '3', '54', '10', '57', '8', '59', '7', '65', '13', '97', '11', '69', '16', '74', '7', '38', '2', '-', '1', '58', '5', '61', '6', '73', '7', '78', '7', '76', '9', '67', '15', '-', '1', '70', '9', '72', '19', '-', '1', '66', '11', '-', '2', '79', '9', '-', '1', '-', '1', '86', '6', '83', '8', '77', '18', '75', '5', '82', '15', '-', '1']

6. Scrape the details of Highest selling novels. 
A) Book name 
B) Author name 
C) Volumes sold 
D) Publisher 
E) Genre 
 Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [11]:
driver = webdriver.Chrome()
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')
Book_name=[]
Author_name=[]
Volumes_sold=[]
Publisher=[]
Genre=[]
#scraping the Book_name 
bname=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]")
for i in bname:
    if i.text is None :
        Book_name.append("--") 
    else:
        Book_name.append(i.text)
print(len(Book_name),Book_name)


#scraping the Author_name 
Auth=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]")
for i in Auth:
    if i.text is None :
        Author_name.append("--") 
    else:
        Author_name.append(i.text)
print(len(Author_name),Author_name)


#scraping the Genre 
gen=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[6]")
for i in gen:
    if i.text is None :
        Genre.append("--") 
    else:
        Genre.append(i.text)
print(len(Genre),Genre)

#scraping the Publisher 
pub=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[5]")
for i in pub:
    if i.text is None :
        Publisher.append("--") 
    else:
        Publisher.append(i.text)
print(len(Publisher),Publisher)

#scraping the Volumes_sold 
vs=driver.find_elements(By.XPATH,"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]")
for i in vs:
    if i.text is None :
        Volumes_sold.append("--") 
    else:
        Volumes_sold.append(i.text)
print(len(Volumes_sold),Volumes_sold)

Book=pd.DataFrame([])
Book['Book_name']=Book_name
Book['Author_name']=Author_name
Book['Genre']=Genre
Book['Publisher']=Publisher
Book['Volumes_sold']=Volumes_sold
Book

100 ['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]
100 ['Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie']
100 ['Crime, Thriller & Adventure', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Romance & Sagas', "Children's Fiction", "Children's Fiction", "Children's Fiction", 'Crime, Thriller & Adventure', "Children's Fiction", 'Romance & Sagas', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Romance & Sagas', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Popular Science', 'Crime, Thriller & Adventure', 'Young Adult Fiction', 'Picture Books', 'Picture Books', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Humour: Collections & General', 'General & Literary Fiction', 'Autobiography: General', 'General & Literary Fiction', 'Biography: The Arts', 'Autobiography: General', 'Picture Books', 'Autobiography: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Science Fiction & Fantasy', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'General & Literary Fiction', 'Fitness & Diet', 'General & Literary Fiction', "Children's Fiction", 'Crime, Thriller & Adventure', 'Fitness & Diet', 'Young Adult Fiction', 'Usage & Writing Guides', 'Food & Drink: General', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Young Adult Fiction', 'General & Literary Fiction', 'Popular Culture & Media: General Interest', 'Autobiography: The Arts', 'General & Literary Fiction', 'Crime, Thriller & Adventure', 'Science Fiction & Fantasy', 'Current Affairs & Issues', 'Crime, Thriller & Adventure', 'Autobiography: The Arts', 'General & Literary Fiction', 'Autobiography: The Arts', 'Travel Writing', 'Food & Drink: General', 'General & Literary Fiction', 'National & Regional Cuisine', 'Fitness & Diet', 'Travel Writing', 'Crime, Thriller & Adventure', 'General & Literary Fiction', 'Food & Drink: General', 'General & Literary Fiction', 'General & Literary Fiction', 'Picture Books', 'General & Literary Fiction', 'Autobiography: The Arts', 'Popular Science', "Children's Annuals", 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'General & Literary Fiction', 'Food & Drink: General', 'Young Adult Fiction', 'Biography: General', 'Food & Drink: General']
100 ['Transworld', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Random House', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Transworld', 'Bloomsbury', 'Random House', 'Little, Brown Book', 'Quercus', 'Random House', 'Transworld', 'Little, Brown Book', 'Transworld', 'Little, Brown Book', 'Pan Macmillan', 'Random House', 'Transworld', 'Transworld', 'Quercus', 'Little, Brown Book', 'Penguin', 'Pan Macmillan', 'Penguin', 'Bloomsbury', 'Hodder & Stoughton', 'Bloomsbury', 'Quercus', 'Random House', 'Random House', 'Pan Macmillan', 'Penguin', 'Random House', 'Random House', 'Canongate', 'HarperCollins', 'Orion', 'Pan Macmillan', 'HarperCollins', 'Random House', 'Scholastic Ltd.', 'Orion', 'Bloomsbury', 'Penguin', 'HarperCollins', 'Random House', 'Little, Brown Book', 'Headline', 'HarperCollins', 'Penguin', 'Orion', 'Bloomsbury', 'Random House', 'Random House', 'Scholastic Ltd.', 'Profile Books Group', 'Random House', 'Transworld', 'Random House Childrens Books G', 'Hodder & Stoughton', 'Scholastic Ltd.', 'Random House', 'HarperCollins', 'Random House', 'Penguin', 'Random House', 'HarperCollins', 'Penguin', 'Headline', 'Little, Brown Book', 'HarperCollins', 'Transworld', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Transworld', 'Transworld', 'Random House', 'Headline', 'Random House', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Hodder & Stoughton', 'Transworld', 'D.C. Thomson', 'Penguin', 'Pan Macmillan', 'Transworld', 'Orion', 'Random House', 'Penguin', 'Scholastic Ltd.', 'Orion', 'Penguin']
100 ['5,094,805', '4,475,152', '4,200,654', '4,179,479', '3,758,936', '3,583,215', '3,484,047', '3,377,906', '3,193,946', '2,950,264', '2,479,784', '2,315,405', '2,233,570', '2,193,928', '2,183,031', '2,152,737', '2,062,145', '2,052,876', '2,005,598', '1,979,552', '1,928,900', '1,852,919', '1,814,784', '1,787,118', '1,783,535', '1,781,269', '1,743,266', '1,629,119', '1,616,068', '1,583,992', '1,555,135', '1,546,886', '1,539,428', '1,508,205', '1,489,403', '1,352,318', '1,310,207', '1,310,176', '1,231,957', '1,217,712', '1,208,711', '1,204,058', '1,184,967', '1,181,503', '1,181,093', '1,153,181', '1,132,336', '1,130,802', '1,126,337', '1,115,549', '1,108,328', '1,107,379', '1,104,403', '1,092,349', '1,090,847', '1,087,262', '1,054,196', '1,037,160', '1,023,688', '1,015,956', '1,009,873', '1,004,414', '1,003,780', '1,002,314', '998,213', '992,846', '986,753', '986,115', '970,509', '967,466', '963,353', '962,515', '959,496', '956,114', '945,640', '931,312', '925,425', '924,695', '906,968', '905,086', '890,847', '869,671', '869,659', '862,602', '856,540', '845,858', '842,535', '828,215', '820,563', '816,907', '816,585', '815,586', '814,370', '809,641', '808,900', '807,311', '794,201', '792,187', '791,507', '791,095']

,Book_name,Author_name,Genre,Publisher,Volumes_sold
0,"Da Vinci Code,The","Brown, Dan","Crime, Thriller & Adventure",Transworld,"5,094,805"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,475,152"
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,200,654"
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.",Children's Fiction,Bloomsbury,"4,179,479"
4,Fifty Shades of Grey,"James, E. L.",Romance & Sagas,Random House,"3,758,936"
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert",General & Literary Fiction,Random House,"807,311"
96,Happy Days with the Naked Chef,"Oliver, Jamie",Food & Drink: General,Penguin,"794,201"
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne",Young Adult Fiction,Scholastic Ltd.,"792,187"
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave",Biography: General,Orion,"791,507"
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie",Food & Drink: General,Penguin,"791,095"

7. Scrape the details most watched tv series of all time from imdb.com. 
Url = https://www.imdb.com/list/ls095964455/ You have 
to find the following details: 
A) Name 
B) Year span 
C) Genre 
D) Run time 
E) Ratings 
F) Votes

updated link- https://www.imdb.com/search/title/?title_type=tv_series&sort=num_votes,desc

In [12]:
driver = webdriver.Chrome()
driver.get('https://www.imdb.com/search/title/?title_type=tv_series&sort=num_votes,desc')
Name=[]
Year_span=[]
Genres=[]
Ratings=[]
Votes=[]
#scraping the Name 
mname=driver.find_elements(By.XPATH,'//div[@class="ipc-title ipc-title--base ipc-title--title ipc-title-link-no-icon ipc-title--on-textPrimary sc-be6f1408-9 srahg dli-title"]/a')
for i in mname:
    if i.text is None :
        Name.append("--") 
    else:
        Name.append(i.text)
print(len(Name),Name)

#scraping the Year_span 
ys=driver.find_elements(By.XPATH,'//div[@class="sc-be6f1408-7 iUtHEN dli-title-metadata"]/span[1]')
for i in ys:
    if i.text is None :
        Year_span.append("--") 
    else:
        Year_span.append(i.text)
print(len(Year_span),Year_span)

#scraping the Genres 
gnr=driver.find_elements(By.XPATH,'//div[@class="ipc-html-content-inner-div"]')
for i in gnr:
    if i.text is None :
        Genres.append("--") 
    else:
        Genres.append(i.text)
print(len(Genres),Genres)



#scraping the Ratings 
rate=driver.find_elements(By.XPATH,'//span[@class="ipc-rating-star ipc-rating-star--base ipc-rating-star--imdb ratingGroup--imdb-rating"]')
for i in rate:
    if i.text is None :
        Ratings.append("--") 
    else:
        Ratings.append(i.text)
print(len(Ratings),Ratings)

#scraping the Votes 
v=driver.find_elements(By.XPATH,'//div[@class="sc-f24f1c5c-0 cPpOqU"]')
for i in v:
    if i.text is None :
        Votes.append("--") 
    else:
        Votes.append(i.text)
print(len(Votes),Votes)

TV_Series=pd.DataFrame([])
TV_Series['Name']=Name
TV_Series['Year_span']=Year_span
TV_Series['Genres']=Genres
TV_Series['Ratings']=Ratings
TV_Series['Votes']=Votes
TV_Series

50 ['1. Game of Thrones', '2. Breaking Bad', '3. Stranger Things', '4. Friends', '5. The Walking Dead', '6. Sherlock', '7. The Big Bang Theory', '8. Dexter', '9. How I Met Your Mother', '10. The Office', '11. True Detective', '12. Peaky Blinders', '13. Better Call Saul', '14. The Boys', '15. Black Mirror', '16. Rick and Morty', '17. Lost', '18. The Mandalorian', '19. Vikings', '20. Prison Break', '21. The Witcher', '22. Squid Game', '23. Westworld', '24. House of Cards', '25. Money Heist', '26. House', '27. The Last of Us', '28. Attack on Titan', '29. Supernatural', '30. Modern Family', '31. Suits', '32. Daredevil', '33. Narcos', '34. The Sopranos', '35. Arrow', '36. Dark', '37. The Simpsons', '38. Fargo', '39. Mr. Robot', '40. Loki', '41. South Park', '42. The Wire', '43. Death Note', '44. The Flash', '45. House of the Dragon', '46. Family Guy', '47. Homeland', '48. Avatar: The Last Airbender', '49. Brooklyn Nine-Nine', '50. Wednesday']
50 ['2011–2019', '2008–2013', '2016–2025', '1994–2004', '2010–2022', '2010–2017', '2007–2019', '2006–2013', '2005–2014', '2005–2013', '2014–', '2013–2022', '2015–2022', '2019–', '2011–', '2013–', '2004–2010', '2019–', '2013–2020', '2005–2017', '2019–', '2021–', '2016–2022', '2013–2018', '2017–2021', '2004–2012', '2023–', '2013–2023', '2005–2020', '2009–2020', '2011–2019', '2015–2018', '2015–2017', '1999–2007', '2012–2020', '2017–2020', '1989–', '2014–2024', '2015–2019', '2021–2023', '1997–', '2002–2008', '2006–2007', '2014–2023', '2022–', '1999–2025', '2011–2020', '2005–2008', '2013–2021', '2022–']
50 ['Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.', "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.", 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.', 'Follows the personal and professional lives of six twenty to thirty year-old friends living in the Manhattan borough of New York City.', 'Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.', 'The quirky spin on Conan Doyle\'s iconic sleuth pitches him as a "high-functioning sociopath" in modern-day London. Assisting him in his investigations: Afghanistan War vet John Watson, who\'s introduced to Holmes by a mutual acquaintance.', 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.', "He's smart. He's lovable. He's Dexter Morgan, America's favorite serial killer, who spends his days solving crimes and nights committing them.", 'A father recounts to his children - through a series of flashbacks - the journey he and his four best friends took leading up to him meeting their mother.', 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.', 'Anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.', 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.', 'The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.', 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.', 'Featuring stand-alone dramas -- sharp, suspenseful, satirical tales that explore techno-paranoia -- "Black Mirror" is a contemporary reworking of "The Twilight Zone" with stories that tap into the collective unease about the modern world.', 'The fractured domestic lives of a nihilistic mad scientist and his anxious grandson are further complicated by their inter-dimensional misadventures.', 'The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.', 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.', 'Vikings transports us to the brutal and mysterious world of Ragnar Lothbrok, a Viking warrior and farmer who yearns to explore--and raid--the distant shores across the ocean.', 'A structural engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence by breaking themselves out from the inside.', 'Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.', "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes: a survival game that has a whopping 45.6 billion-won prize at stake.", 'At the intersection of the near future and the reimagined past, waits a world in which every human appetite can be indulged without consequence.', 'A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.', 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.', 'Using a crack team of doctors and his wits, an antisocial maverick doctor specializing in diagnostic medicine does whatever it takes to solve puzzling cases that come his way.', "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.", 'After his hometown is destroyed and is traumatized, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.', "Two brothers follow their father's footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.", 'Three different, but related, families face trials and tribulations in their own uniquely comedic ways.', "On the run from a drug deal gone bad, brilliant college dropout Mike Ross finds himself working with Harvey Specter, one of New York City's best lawyers.", 'A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.', 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.', 'New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.', 'Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.', 'A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.', 'The satiric adventures of a working-class family in the misfit city of Springfield.', 'Various chronicles of deception, intrigue, and murder in and around frozen Minnesota. All of these tales mysteriously lead back one way or another to Fargo, North Dakota.', 'Elliot, a brilliant but unstable cyber-security engineer and vigilante hacker, becomes a key figure in a complex game of global chaos when he and his shadowy allies try to take down the corrupt corporation his company is paid to protect.', 'The mercurial villain Loki resumes his role as the God of Mischief in a new series that takes place after the events of “Avengers: Endgame.”', 'Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.', 'The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.', 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.', "After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash, and fighting crime in Central City.", 'An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.', 'In a wacky Rhode Island town, a dysfunctional family strives to cope with everyday life as they are thrown from one crazy scenario to another.', 'A bipolar CIA operative becomes convinced a prisoner of war has been turned by al-Qaeda and is planning to carry out a terrorist attack on American soil.', 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.', "Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD's 99th Precinct.", "Follows Wednesday Addams' years as a student, when she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents."]
50 ['9.2\n (2.3M)', '9.5\n (2.1M)', '8.7\n (1.3M)', '8.9\n (1.1M)', '8.1\n (1.1M)', '9.1\n (988K)', '8.1\n (860K)', '8.7\n (759K)', '8.3\n (723K)', '9.0\n (699K)', '8.9\n (642K)', '8.8\n (636K)', '9.0\n (636K)', '8.7\n (634K)', '8.7\n (632K)', '9.1\n (594K)', '8.3\n (590K)', '8.7\n (580K)', '8.5\n (575K)', '8.3\n (574K)', '8.0\n (565K)', '8.0\n (531K)', '8.5\n (529K)', '8.6\n (528K)', '8.2\n (526K)', '8.7\n (504K)', '8.8\n (501K)', '9.1\n (498K)', '8.4\n (479K)', '8.5\n (477K)', '8.4\n (471K)', '8.6\n (471K)', '8.8\n (465K)', '9.2\n (462K)', '7.5\n (445K)', '8.7\n (437K)', '8.7\n (433K)', '8.9\n (416K)', '8.5\n (415K)', '8.2\n (406K)', '8.7\n (403K)', '9.3\n (373K)', '8.9\n (372K)', '7.5\n (367K)', '8.4\n (363K)', '8.2\n (362K)', '8.3\n (359K)', '9.3\n (358K)', '8.4\n (356K)', '8.1\n (353K)']
50 ['Votes2,259,560', 'Votes2,107,067', 'Votes1,318,362', 'Votes1,077,563', 'Votes1,070,563', 'Votes988,455', 'Votes860,250', 'Votes758,946', 'Votes723,472', 'Votes698,743', 'Votes641,996', 'Votes636,470', 'Votes635,628', 'Votes633,784', 'Votes632,419', 'Votes593,833', 'Votes589,774', 'Votes579,762', 'Votes575,362', 'Votes574,402', 'Votes564,639', 'Votes530,530', 'Votes529,315', 'Votes527,970', 'Votes526,030', 'Votes504,334', 'Votes501,113', 'Votes497,793', 'Votes478,597', 'Votes476,546', 'Votes471,417', 'Votes470,917', 'Votes465,207', 'Votes462,012', 'Votes444,599', 'Votes437,139', 'Votes432,702', 'Votes415,710', 'Votes414,829', 'Votes406,130', 'Votes403,078', 'Votes372,657', 'Votes372,090', 'Votes366,768', 'Votes363,179', 'Votes361,696', 'Votes359,066', 'Votes357,577', 'Votes355,712', 'Votes352,748']

,Name,Year_span,Genres,Ratings,Votes
0,1. Game of Thrones,2011–2019,Nine noble families fight for control over the...,9.2\n (2.3M),"Votes2,259,560"
1,2. Breaking Bad,2008–2013,A chemistry teacher diagnosed with inoperable ...,9.5\n (2.1M),"Votes2,107,067"
2,3. Stranger Things,2016–2025,"When a young boy vanishes, a small town uncove...",8.7\n (1.3M),"Votes1,318,362"
3,4. Friends,1994–2004,Follows the personal and professional lives of...,8.9\n (1.1M),"Votes1,077,563"
4,5. The Walking Dead,2010–2022,Sheriff Deputy Rick Grimes wakes up from a com...,8.1\n (1.1M),"Votes1,070,563"
5,6. Sherlock,2010–2017,The quirky spin on Conan Doyle's iconic sleuth...,9.1\n (988K),"Votes988,455"
6,7. The Big Bang Theory,2007–2019,A woman who moves into an apartment across the...,8.1\n (860K),"Votes860,250"
7,8. Dexter,2006–2013,"He's smart. He's lovable. He's Dexter Morgan, ...",8.7\n (759K),"Votes758,946"
8,9. How I Met Your Mother,2005–2014,A father recounts to his children - through a ...,8.3\n (723K),"Votes723,472"
9,10. The Office,2005–2013,A mockumentary on a group of typical office wo...,9.0\n (699K),"Votes698,743"
10,11. True Detective,2014–,Anthology series in which police investigation...,8.9\n (642K),"Votes641,996"
11,12. Peaky Blinders,2013–2022,"A gangster family epic set in 1900s England, c...",8.8\n (636K),"Votes636,470"
12,13. Better Call Saul,2015–2022,The trials and tribulations of criminal lawyer...,9.0\n (636K),"Votes635,628"
13,14. The Boys,2019–,A group of vigilantes set out to take down cor...,8.7\n (634K),"Votes633,784"
14,15. Black Mirror,2011–,"Featuring stand-alone dramas -- sharp, suspens...",8.7\n (632K),"Votes632,419"
15,16. Rick and Morty,2013–,The fractured domestic lives of a nihilistic m...,9.1\n (594K),"Votes593,833"
16,17. Lost,2004–2010,The survivors of a plane crash are forced to w...,8.3\n (590K),"Votes589,774"
17,18. The Mandalorian,2019–,The travels of a lone bounty hunter in the out...,8.7\n (580K),"Votes579,762"
18,19. Vikings,2013–2020,Vikings transports us to the brutal and myster...,8.5\n (575K),"Votes575,362"
19,20. Prison Break,2005–2017,A structural engineer installs himself in a pr...,8.3\n (574K),"Votes574,402"
20,21. The Witcher,2019–,"Geralt of Rivia, a solitary monster hunter, st...",8.0\n (565K),"Votes564,639"
21,22. Squid Game,2021–,Hundreds of cash-strapped players accept a str...,8.0\n (531K),"Votes530,530"
22,23. Westworld,2016–2022,At the intersection of the near future and the...,8.5\n (529K),"Votes529,315"
23,24. House of Cards,2013–2018,A Congressman works with his equally conniving...,8.6\n (528K),"Votes527,970"
24,25. Money Heist,2017–2021,An unusual group of robbers attempt to carry o...,8.2\n (526K),"Votes526,030"
25,26. House,2004–2012,"Using a crack team of doctors and his wits, an...",8.7\n (504K),"Votes504,334"
26,27. The Last of Us,2023–,"After a global pandemic destroys civilization,...",8.8\n (501K),"Votes501,113"
27,28. Attack on Titan,2013–2023,After his hometown is destroyed and is traumat...,9.1\n (498K),"Votes497,793"
28,29. Supernatural,2005–2020,Two brothers follow their father's footsteps a...,8.4\n (479K),"Votes478,597"
29,30. Modern Family,2009–2020,"Three different, but related, families face tr...",8.5\n (477K),"Votes476,546"
30,31. Suits,2011–2019,"On the run from a drug deal gone bad, brillian...",8.4\n (471K),"Votes471,417"
31,32. Daredevil,2015–2018,"A blind lawyer by day, vigilante by night. Mat...",8.6\n (471K),"Votes470,917"
32,33. Narcos,2015–2017,A chronicled look at the criminal exploits of ...,8.8\n (465K),"Votes465,207"
33,34. The Sopranos,1999–2007,New Jersey mob boss Tony Soprano deals with pe...,9.2\n (462K),"Votes462,012"
34,35. Arrow,2012–2020,Spoiled billionaire playboy Oliver Queen is mi...,7.5\n (445K),"Votes444,599"
35,36. Dark,2017–2020,"A family saga with a supernatural twist, set i...",8.7\n (437K),"Votes437,139"
36,37. The Simpsons,1989–,The satiric adventures of a working-class fami...,8.7\n (433K),"Votes432,702"
37,38. Fargo,2014–2024,"Various chronicles of deception, intrigue, and...",8.9\n (416K),"Votes415,710"
38,39. Mr. Robot,2015–2019,"Elliot, a brilliant but unstable cyber-securit...",8.5\n (415K),"Votes414,829"
39,40. Loki,2021–2023,The mercurial villain Loki resumes his role as...,8.2\n (406K),"Votes406,130"
40,41. South Park,1997–,Follows the misadventures of four irreverent g...,8.7\n (403K),"Votes403,078"
41,42. The Wire,2002–2008,"The Baltimore drug scene, as seen through the ...",9.3\n (373K),"Votes372,657"
42,43. Death Note,2006–2007,An intelligent high school student goes on a s...,8.9\n (372K),"Votes372,090"
43,44. The Flash,2014–2023,"After being struck by lightning, Barry Allen w...",7.5\n (367K),"Votes366,768"
44,45. House of the Dragon,2022–,An internal succession war within House Targar...,8.4\n (363K),"Votes363,179"
45,46. Family Guy,1999–2025,"In a wacky Rhode Island town, a dysfunctional ...",8.2\n (362K),"Votes361,696"
46,47. Homeland,2011–2020,A bipolar CIA operative becomes convinced a pr...,8.3\n (359K),"Votes359,066"
47,48. Avatar: The Last Airbender,2005–2008,"In a war-torn world of elemental magic, a youn...",9.3\n (358K),"Votes357,577"
48,49. Brooklyn Nine-Nine,2013–2021,Comedy series following the exploits of Det. J...,8.4\n (356K),"Votes355,712"
49,50. Wednesday,2022–,"Follows Wednesday Addams' years as a student, ...",8.1\n (353K),"Votes352,748"

 
8. Details of Datasets from UCI machine learning repositories. 
Url = https://archive.ics.uci.edu/ You 
have to find the following details: 
A) Dataset name 
B) Data type 
C) Task 
D) Attribute type 
E) No of instances 
F) No of attribute G) Year 
 Note: - from the home page you have to go to the Show All Dataset page through code.

In [13]:
driver = webdriver.Chrome()
driver.get('https://archive.ics.uci.edu/ml/index.php')
view_data = driver.find_element(By.XPATH,'//div[@class="flex flex-wrap justify-center gap-5"]/a') 
view_data.click()
Dataset_Name=[]
Data_Type_Attribute_Type_No_of_Instances_No_of_Attribute=[]

#scraping the Dataset_Name 
dname=driver.find_elements(By.XPATH,'//div[@class="relative col-span-8 sm:col-span-7"]/h2')
for i in dname:
    if i.text is None :
        Dataset_Name.append("--") 
    else:
        Dataset_Name.append(i.text)
print(len(Dataset_Name),Dataset_Name)


dtype=driver.find_elements(By.XPATH,'//div[@class="my-2 hidden gap-4 md:grid grid-cols-12"]/div/span')
for i in dtype:
    if i.text is None :
        Data_Type_Attribute_Type_No_of_Instances_No_of_Attribute.append("--") 
    else:
        Data_Type_Attribute_Type_No_of_Instances_No_of_Attribute.append(i.text)
print(len(Data_Type_Attribute_Type_No_of_Instances_No_of_Attribute),Data_Type_Attribute_Type_No_of_Instances_No_of_Attribute)

10 ['Iris', 'Dry Bean Dataset', 'Heart Disease', 'Rice (Cammeo and Osmancik)', 'Adult', 'Raisin', 'Wine', 'Breast Cancer Wisconsin (Diagnostic)', 'Wine Quality', 'Diabetes']
40 ['Classification', 'Tabular', '150 Instances', '4 Features', 'Classification', 'Multivariate', '13.61K Instances', '16 Features', 'Classification', 'Multivariate', '303 Instances', '13 Features', 'Classification', 'Multivariate', '3.81K Instances', '7 Features', 'Classification', 'Multivariate', '48.84K Instances', '14 Features', 'Classification', 'Multivariate', '900 Instances', '8 Features', 'Classification', 'Tabular', '178 Instances', '13 Features', 'Classification', 'Multivariate', '569 Instances', '30 Features', 'Classification, Regression', 'Multivariate', '4.9K Instances', '12 Features', 'Classification', 'Multivariate, Time-Series', '1 Instances', '20 Features']